//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub email: String,
    pub email_verified: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub accounts: HasMany<super::accounts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
